### ISSUE TITLE
Comments for Date: 2014-03-18

### ISSUE THREAD

**Issue by gmhawash** [renewablefunding/sheng#1]
The structure of the gem is definitely better than the first release.  Some followup comments below:

1. Provide an integration test which validates that the content of output document is the same as the template output document.  At the very least, a comparison of that the unzipped XML content of the produced document are the same as the unzipped XML content of the template output document.

2. Unit level tests for the set of ‘replace’ and helper methods.

3. avoid singleton methods, if possible; e.g., change ‘self.replace’ to instance method.  Ideally, use the helpers as instance methods (include) rathern than class methods (extend).

**Comment by ravigadad** [comment]
Closing; not applicable to rewritten code
